apiVersion: batch/v1
kind: Job
metadata:
  name: hive-initschema
  namespace: hive
spec:
  template:
    spec:
      containers:
      - name: hivemeta
        image: gcr.io/ggke-401900/hive-metastore
        command: ["/opt/hive-metastore/bin/schematool"]
        args: ["--verbose", "-initSchema", "-dbType", "mysql", "-userName", "mjs",
          "-passWord", "1234", "-url", "jdbc:mysql://mysql.mysql.svc.cluster.local:3306/test?useSSL=false"]
      restartPolicy: Never
  backoffLimit: 4